### ISSUE TITLE
【前端】secret 编辑支持JSON编辑

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/serverless-cd#28]

**Comment by g-fengchen** [comment]
https://github.com/Serverless-Devs/serverless-cd/pull/32

**Comment by xsahxl** [comment]
> #32

创建流程是不是也需要支持下？
![image](https://user-images.githubusercontent.com/21330840/207486467-c9402aa4-9590-4f6c-8539-053aae804b4a.png)
