### ISSUE TITLE
应用市场功能建设

### ISSUE THREAD

**Issue by heimanba** [Serverless-Devs/serverless-cd#50]
# 创建流程
创建流程为：
![image](https://user-images.githubusercontent.com/5129967/207896795-7ce40a4d-b63f-4c51-b605-f927ed53fe7f.png)

# 包管理方案
### 包管理(通过NPM)
![image](https://user-images.githubusercontent.com/5129967/207895415-90a0fbe3-26a3-4910-b61e-f9be60d0c5ab.png)

### 优点
monorepo对于统一项目管理非常方便。
#### 缺点
无法实现单独仓库的fork

### 单独serverless-cd仓库
https://github.com/serverless-cd-demo

#### 优点：
很好的支持每个仓库fork的需求

#### 缺点：
无法很好的进行管理，比如如何进行统一升级等

**Comment by heimanba** [comment]
## 问题：
如何拿到模版列表？
### 方案1
https://api.github.com/orgs/serverless-cd-demo/repos

#### 缺点
1. 如何统一维护 描述等信息？
2. 如何进行分类
3. 是不是所有的模版都基于github来存储？需要兼容 gitee...
4. github 频繁请求会限流。。。一定要做本地缓存

#### 优点
简单/快速

### 方案2
自己实现一个简单的管理后台。。。。
#### 缺点
比较复杂，太多依赖
#### 优点
灵活度非常高

**Comment by anycodes** [comment]
这个模板列表，还是要用咱们serverless regitry，直接对接registry就可以

**Comment by heimanba** [comment]
> 



> 这个模板列表，还是要用咱们serverless regitry，直接对接registry就可以

可以的，这里需要registry 单独给一个列表的接口哈，能够单独进行查询。

**Comment by heimanba** [comment]
done
